### Server Configuration
server:
  port: 8092
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true


### Logging Configuration
logging:
  level:
    io.swagger.models.parameters.AbstractSerializableParameter: ERROR
# https://github.com/springfox/springfox/issues/2776#issuecomment-600405932
# *** https://blog.karatos.in/a?ID=00950-7a1f5c4c-1e88-40e4-b5bb-5244dc110e2f


### Spring Configuration
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: client secret id
            clientSecret: client secret key
          naver:
            clientId: client secret id
            clientSecret: client secret key
            redirectUri: client uri
            authorizationGrantType: authorization_code
            clientName: naver
        provider:
          naver:
            authorization-uri: authorization-uri 
            token-uri: token-uri
            user-info-uri: user-info-uri
            user-name-attribute: response

  servlet:
    multipart:
      max-file-size: 1000MB
      maxRequestSize: 1000MB
  mvc:
    static-path-pattern: /files/**

  ### Datasource
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc url
    username: username
    password: password

  ### JPA
  jpa:
#    show-sql: false

    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy:  physical-strategy

#    properties:
#      hibernate:
#        format_sql: true

